name: Go Build CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Verify dependencies
      run: go mod download

    - name: Build static binary
      run: CGO_ENABLED=0 GOOS=linux go build -o it-asset-manager .
